name: Sheets Loader & Charts

on:
  workflow_dispatch:

jobs:
  sheets-loader:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install gspread google-auth pandas matplotlib pytz
          sudo apt-get install -y jq

      - name: Create service account file
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS_JSON }}' | jq . > "$GITHUB_WORKSPACE/service_account.json"
          test -s "$GITHUB_WORKSPACE/service_account.json" || { echo "Credentials file is empty"; exit 1; }
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}

      - name: Run Sheets Loader for Sheet 1
        env:
          SHEET_ID2: ${{ secrets.SHEET_ID2 }}
          GOOGLE_CREDENTIALS_PATH: ${{ github.workspace }}/service_account.json
        run: python sheets_loader.py
