name: Generate Charts

on:
  workflow_dispatch:   # manual trigger
  schedule:
    - cron: "0 * * * *"   # runs every hour

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install gspread pandas oauth2client matplotlib streamlit

      # Run your script that fetches Sheets + generates charts
      - name: Run chart generator
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          python charts.py

      # (Optional) Upload charts as workflow artifacts
      - name: Upload generated charts
        uses: actions/upload-artifact@v4
        with:
          name: charts
          path: charts_output/   # <-- wherever your script saves charts
